export interface UserInfo {
  mutual: boolean,
  remarkName?: string,
  avatarImgId: number,
  backgroundImgId: number,
  detailDescription: string,
  avatarImgIdStr: string,
  backgroundImgIdStr: string,
  defaultAvatar: boolean,
  expertTags?: string,
  djStatus: number,
  followed: boolean,
  backgroundUrl: string,
  gender: number,
  birthday: number,
  city: number,
  avatarUrl: string,
  authStatus: number,
  userType: number,
  nickname: string,
  accountStatus: number,
  vipType: number,
  province: number,
  description: string,
  userId: number,
  signature: string,
  authority: number
}
